server:
  port: 4000
  shutdown: graceful

app:
  version: "1.0.0"
  env: "development"
  mailer:
    sender: "Greenlight <no-reply@sohail.world>"

spring:
  application:
    name: greenlight-spring
  datasource:
    url: ${NEON_DB_URL}
    username: ${NEON_DB_USER}
    password: ${NEON_DB_PASSWORD}
  lifecycle:
    timeout-per-shutdown-phase: 20s
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: false