CREATE TABLE movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    year INTEGER NOT NULL,
    runtime INTEGER NOT NULL,
    image_url VARCHAR(2048) NOT NULL,
    synopsis VARCHAR(1000) NOT NULL
);

CREATE TABLE movie_genres (
    movie_id BIGINT NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
    genre_order INTEGER NOT NULL,
    genre VARCHAR(50) NOT NULL,
    PRIMARY KEY (movie_id, genre_order)
);
